export const LogoText = "Modnikky";
export const NavMenuNewArrivals = "New Arrivals";
export const NavMenuShop = "Shop";
export const NavMenuCollections = "Collections";
export const NavMenuSearch = "Search";
export const NavMenuSignIn = "Sign In";
export const NavMenuSignUp = "Sign Up";
export const NavMenuSignOut = "Sign Out";
export const NavMenuBag = "Bag";
export const NavMenuFavorites = "Favorites";
export const TopSectionTitleText = "New collection";
export const TopSectionDescriptionText =
  "Our easiest chuck-on-and-go staples come with a serious style heritage" +
  "\n that’s liberating, sexy, comfy and supremely cool. ";
export const TopSectionButtonText = "Shop new arrival";
export const SortedSectionButtonText = "Show more";
export const SubscriptionSectionTitleText = "Sign up for updates";
export const SubscriptionDescriptionText =
  "Sign up for exclusive early sale access and tailored new arrivals.";
export const FooterCardCustomer = "customer service";
export const FooterCardContact = "contact";
export const FooterCardTrack = "track order";
export const FooterCardDelivery = "delivery & returns";
export const FooterCardPayment = "payment";
export const FooterCardReturn = "make a return";
export const FooterCardFAQ = "FAQ";
export const FooterCardInfo = "info";
export const FooterCardGift = "gift vouchers";
export const FooterCardGuide = "size guide";
export const FooterCardCareers = "careers at modnikky";
export const FooterCardAbout = "about us";
export const FooterCardPolicies = "legal policies";
export const FooterCardFacebook = "facebook";
export const FooterCardOdnoklassniki = "odnoklassniki";
export const FooterCardEmail = "hello@modnikky.com";
export const FooterCardPhone = "+7 910 832 26XX";
export const FooterCardAddress = "Visit us at Shalalaeva 23,\n Bologoe, Russia";
export const Instagram = "instagram";
export const FooterCardContactInfo = "contact us";
export const FooterCardFollow = "follow us";
export const SectionTitleShopText = "Shop by the";
export const SectionTitleCategoryText = " Category";
export const LogoHashtag = "#MODNIKKY";
export const SaleHashtag = "_Sale";
export const ShopText = "shop";
export const CategoryDresses = "Dresses";
export const CategoryTees = "Tees";
export const CategorySwimwear = "Swimwear";
export const CategoryDenim = "Denim";
export const CategoryTops = "Tops";
export const CategoryBeauty = "Beauty";
export const ProductDescription = "Product Description";
export const ShippingReturns = "shipping & returns";
export const ShippingReturnsText =
  "Delivery and returns are always free on all orders. Standard delivery takes place approximately within 3-4 working days (5-6 working days in selected countries) from the moment in which the order leaves the warehouse. All orders are processed Monday to Friday, excluding holidays. More detailed information will be provided during the purchasing process. To check the shipping times for each country and the shipping methods available visit the section CUSTOMER SERVICE.\n" +
  "\n" +
  "We remind you that this information does not apply in the case of pre-orders, personalized items, and items from the Food&Beverage section. You will find information on returns and delivery times in the respective product data sheets.";
export const CareAndDetails = "Care and details";
export const CareAndDetailsText = "External composition: 100% Cotton";
export const CreateAccount = "Create Account";
export const RegisterCheckbox =
  "Let's get personal! We'll send you only the good stuff: \n Exclusive early access to Sale, new arrivals and promotions. No nasties.";
export const TermsOfService = "Terms of Service";
export const PrivacyPolicy = "Privacy Policy";
export const HaveAccount = "I have an account";
export const DoNotHaveAccount = "I don't have an account";
export const SearchSectionInputPlaceholder = "enter search terms";
export const SearchResults = "Search results";
export const ItemsText = "items";
export const ItemText = "item";
export const ColorText = "color";
export const SizeText = "size";
export const QuantityText = "quantity";
export const RemoveText = "remove";
export const EmptyBag = "There are no items in the bag to order.";
export const EmptyFavorites = "There are no items in the favorites.";
export const TotalUSDText = "Total USD $";
export const CheckoutText = "Proceed to checkout";
export const AddingToBag = "Add to bag";
